---
title: "figure 1 of Watson and Lovelock"
author: "Robin KS Hankin"
date: "20/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("usefulfuncs.R")
```

The canonical reference is:

A. J. Watson and J. E. Lovelock 1983. "Biological homeostasis of the
global environment: the parable of Daisyworld".  _Tellus_ 35B:284--289

First, define a function `daisy()` that runs the ODE and returns the
equilibrium configuration;

```{r definedaisy}
daisy <- function(parameters, ..., all=FALSE){  # something like daisy(params, L=1.2,all=T)
  a <- list(...)
  element <- names(a)
  value <- as.numeric(a)
  parameters[[element]] <- value
  initial_state <- c(W=0.8, B=0.1) # initial value. NB: figure 1 is sensitive to this!  
  times <- seq(0, 10, by = 1)      # times for output
  jj <- ode(y = initial_state, times = times, func = watson, parms = parameters)
  if(all){
    out <- jj
  } else {
    out <- c(jj[nrow(jj),-1])  # column 1 of jj is 'time'
  }
  out <- c(value,out)
  names(out) <-c(element,"W","B","T_e")
  return(out)
}

```

Now we can run `daisy()` across a range of luminosity `L`:

```{r usedaisy}

L <- seq(from=0.6,to=2,by=0.02)
M <- matrix(0,length(L),4)

for(i in seq_along(L)){
  M[i,] <- daisy(parameters,L=L[i])
}
colnames(M) <- c("L","W","B","T_e")
head(M)
plot(T_e~L,data=M,type='b')
plot(W~L,data=M,type='b',pch=1)
points(B~L,data=M,type='b',pch=16)
```


Now the same graphs again but we will superimpose Hankin and Mitchell in red:


```{r hankinmitchell}
p_HM <- parameters
p_HM$gamma <- 0
M_old <- M # previous chunk
M <- matrix(0,length(L),4)

for(i in seq_along(L)){
  M[i,] <- daisy(p_HM,L=L[i])
}
colnames(M) <- c("L","W","B","T_e")


plot(T_e~L,data=M_old,type='b',main="planetary temperature as a function of luminosity")
points(T_e~L,data=M,type='b',col='red')
legend("topleft",col=c("black","red"),legend=c("Watson and Lovelock","Hankin and Mitchell")
,lty=1,pch=1)


plot(W~L,data=M_old,type='b',pch=1,ylim=0:1,main="White and black daisy coverage as a function of luminosity")
points(B~L,data=M_old,type='b',pch=16)

points(W~L,data=M,type='b',pch=1,col='red')
points(B~L,data=M,type='b',pch=16,col='red')
```
